baseURL = "/"
languageCode = "en-us"
title = "Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    ourvision = "display"
    subtitle = ""
    subsite = "default"
    openGraphSiteName = "Tracking Exposed"
    description = "We develop free software to enable research and expert users in figuring out how algorithms shape their online perception."
    tagline = "We develop tools to uncover how tracking and profiling have an impact on society"


[permalinks]
    posts = "/v0/post/:slug/"
    pr = "/press/releases/:slug/"
    blog = "/blog/:slug"


[menu]

 [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 10

 [[menu.main]]
    name = "Manifesto"
    url = "/manifesto"
    weight = 15


 [[menu.main]]
    page = "Tools"
    name = "Tools"
    identifier = "tools"
    weight = 20
 [[menu.main]]
    page = "Facebook"
    identifier = "facebook"
    parent = "tools"
    name= "Facebook"
    url = "https://facebook.tracking.exposed"
    weight = -180
 [[menu.main]]
    page = "YouTube"
    parent = "tools"
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.tracking.exposed"
    weight = -170
 [[menu.main]]
    page = "PornHub"
    parent = "tools"
    identifier = "pornhub"
    name = "PornHub"
    url = "https://pornhub.tracking.exposed"
    weight = -160
 [[menu.main]]
    page = "TikTok"
    parent = "tools"
    identifier = "tiktok"
    name = "TikTok"
    url = "https://tiktok.tracking.exposed"
    weight = -150

 [[menu.main]]
    name = "Impact"
    identifier = "impact"
    url = "/impact/"
    weight = 40

 [[menu.main]]
    parent = "impact"
    name = "Publications"
    url = "/publications/"
    weight = 10
 [[menu.main]]
    parent = "impact"
    name = "Press Coverage"
    url ="/press/"
    weight = 20
 [[menu.main]]
    parent = "impact"
    name = "Videos"
    url = "/videos/"
    weight = 30
 [[menu.main]]
    parent = "impact"
    name = "Events"
    url = "/events/"
    weight = 40
 [[menu.main]]
    parent = "impact"
    name = "Progress Reports"
    url = "/monthly/"
    weight = 40
 [[menu.main]]
    parent = "impact"
    name = "Press Releases"
    url = "/pr/"
    weight = 50

 [[menu.footer]]
    page = "manifesto"
    identifier = "manifesto"
    name= "Manifesto"
    url = "/manifesto"
    weight =10
 [[menu.footer]]
    page = "tools"
    identifier = "tools"
    name = "Tools"
    url = "/connect"
    weight = 20
 [[menu.footer]]
    page = "connections"
    identifier = "connections"
    name = "Connections"
    url ="/about"
    weight = 30
 [[menu.footer]]
    page = "impact"
    name = "Impact"
    identifier = "impact"
    url = "/impact"
    weight = 40

 [[menu.featured]]
    name= "Manifesto"
    url = "/manifesto"
    weight = -180
    pre = "/images/reports.svg"
    post = "Since 2016 we fight for a web that is home for many, not property of the few. ðŸ’¡ Our beliefs are guiding us towards our purpose: empowering people."
 [[menu.featured]]
    name = "Connections"
    url = "/about"
    weight = -170
    pre = "/images/connect with us.svg"
    post = "Who we are and who is supporting us.ðŸŽˆ If you wish to get involved, feel free to reach us out, any collaboration is more than welcome."
 [[menu.featured]]
    name = "Investigative Report"
    url = "/pdf/tiktok-russia-15march2022.pdf"
    weight = -190
    pre = "/images/trex-logo.svg"
    post = "15 March 2022 - TikTok blocks 95% of content for users in Russia"
