baseURL = "/"
languageCode = "en-us"
title = "Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    ourvision = "display"
    subtitle = ""
    subsite = "default"
    openGraphSiteName = "Tracking Exposed"
    description = "We develop free software to enable research and expert users in figuring out how algorithms shape their online perception."
    tagline = "We develop tools to uncover how tracking and profiling have an impact on society"


[permalinks]
    posts = "/news/:slug/"

[menu]


 [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 10

 [[menu.main]]
    name = "Manifesto"
    url = "/manifesto"
    weight = 15


 [[menu.main]]
    page = "Tools"
    name = "Tools"
    identifier = "tools"
    weight = 20
 [[menu.main]]
    page = "Facebook"
    identifier = "facebook"
    parent = "tools"
    name= "Facebook"
    url = "https://facebook.tracking.exposed"
    weight = -180
 [[menu.main]]
    page = "YouTube"
    parent = "tools"
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.tracking.exposed"
    weight = -170
 [[menu.main]]
    page = "PornHub"
    parent = "tools"
    identifier = "pornhub"
    name = "PornHub"
    url = "https://pornhub.tracking.exposed"
    weight = -160




# [[menu.main]]
#    parent = "connections"
#    name = "Contacts"
#    url = "/connections/"
#    weight = 10
# [[menu.main]]
#    parent = "connections"
#    name = "Team"
#    url ="/connections/#team"
#    weight = 20
# [[menu.main]]
#    parent = "connections"
#    name = "Partners"
#    url = "/connections/#partners"
#    weight = 30



 [[menu.main]]
    name = "Impact"
    identifier = "impact"
    url = "/impact/"
    weight = 40

 [[menu.main]]
    parent = "impact"
    name = "Publications"
    url = "/publications/"
    weight = 10
 [[menu.main]]
    parent = "impact"
    name = "Press"
    url ="/press/"
    weight = 20
 [[menu.main]]
    parent = "impact"
    name = "Videos"
    url = "/videos/"
    weight = 30
 [[menu.main]]
    parent = "impact"
    name = "Events"
    url = "/events/"
    weight = 40
 [[menu.main]]
    parent = "impact"
    name = "Monthly Reports"
    url = "/monthly/"
    weight = 40




#  [[menu.main]]
#    page = "A national-declined research (Italian election)"
#    identifier = "eu19.tracking.exposed"
#    name = "EU Election 2019"
#    parent = "studies"
#    url = "https://eu19.tracking.exposed"
#    weight = -100
#  [[menu.main]]
#    page = "A national-declined research (Italian election)"
#    identifier = "elezioni.tracking.exposed"
#    parent = "studies"
#    name = "Italien Election"
#    url = "https://elezioni.tracking.exposed"
#    weight = -100
# [[menu.main]]
#    page = "PornHub"
#    identifier = "pornhub"
#    parent = "analyzed"
#    name = "PornHub"
#    url = "https://pornhub.tracking.exposed"
#    weight = -160


 [[menu.footer]]
    page = "manifesto"
    identifier = "manifesto"
    name= "Manifesto"
    url = "/manifesto"
    weight =10
 [[menu.footer]]
    page = "tools"
    identifier = "tools"
    name = "Tools"
    url = "/connect"
    weight = 20
 [[menu.footer]]
    page = "connections"
    identifier = "connections"
    name = "Connections"
    url ="/connections"
    weight = 30
 [[menu.footer]]
    page = "impact"
    name = "Impact"
    identifier = "impact"
    url = "/impact"
    weight = 40

 [[menu.featured]]
    name= "Manifesto"
    url = "/manifesto"
    weight = -180
    pre = "/images/trex-logo.svg"
    post = "Since 2016 we fight for a web that is home for many, not property of the few. ðŸ’¡ Our beliefs are guiding us towards our purpose: empowering people."
 [[menu.featured]]
    name = "Connections  "
    url = "/connections"
    weight = -170
    pre = "/images/connect with us.svg"
    post = "Who we are and who is supporting us.ðŸŽˆ If you wish to get involved, feel free to reach us out, any collaboration is more than welcome."
 [[menu.featured]]
    name = "Impact"
    url = "/impact"
    weight = -160
    pre = "/images/reports.svg"
    post = "Our last activities, publications and appearances, ðŸ”­ from all the various project under the tracking.exposed umbrella."
